tee .pr-describer.yml > /dev/null <<'YML'
style: conventional-commit      # casual | formal | conventional-commit
summary_length: 100             # target words
min_changed_lines: 5            # skip tiny PRs unless forced
post_mode: comment              # comment | overwrite

labels:
  skip: ["no-ai", "draft"]
  force: ["ai-describe"]
YML
