import { Octokit } from "@octokit/rest";
import { generateFromDiff } from "./lib/generator.js";

const token = process.env.GITHUB_TOKEN;
const [owner, repo] = process.env.REPO_FULL.split("/");
const pr = Number(process.env.PR_NUMBER);
const octo = new Octokit({ auth: token });

// Get changed files/patches
const files = await octo.pulls.listFiles({ owner, repo, pull_number: pr, per_page: 100 });

let diff = "";
for (const f of files.data) {
  if (f.patch) diff += `\n# ${f.filename}\n${f.patch}\n`;
}

// Call your generator (trim to keep token usage tidy)
const suggestion = await generateFromDiff({
  diff: diff.slice(0, 12000),
  repo: `${owner}/${repo}`,
  author: "bot"
});

// Comment the suggestion on the PR
await octo.issues.createComment({
  owner, repo, issue_number: pr,
  body: [
    "### 🤖 Suggested PR Title & Description",
    "",
    "```",
    suggestion,
    "```",
    "_Generated by pr-copilot-extension_"
  ].join("\n")
});
console.log("Comment posted.");
