name: PR AI Describer

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
  push:
    branches: [main]

jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - name: Always succeed
        run: echo "Workflow stubbed — passing ✅"
